branches:
  only:
  - master
language: node_js
sudo: false
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_5cd716f23a63_key -iv $encrypted_5cd716f23a63_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "Abner"
- git config --global user.email contact@abnerchou.me
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo g
- hexo d
