name: deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
    - name: deploy
      uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
          repo-token: ${{ secrets.GH_TOKEN }}
          site-directory: "public"
